version: 2.1

orbs:
  node: circleci/node@4.1

commands:
  run_install_dependencies:
    steps:
      - run:
          name: Install Dependencies
          command: |
            cd ./src/backend
            yarn install
            yarn migrate:test-ci
            yarn prisma generate
  run_lint_check:
    steps:
      - run:
          name: Run Lint Check
          command: |
            cd ./src/backend
            yarn eslint
  run_test:
    steps:
      - run:
          name: Run Unit and Integration testing
          command: |
            cd ./src/backend
            yarn test-ci
  run_bump_version:
    steps:
      - run:
          name: Bump Version



executors:
  app_docker:
    docker:
      - image: cimg/node:12.18.3
        environment:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          REDIS_PASS: password
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: testdb
      - image: circleci/redis:6.0.8-alpine
        command: ["redis-server", "--requirepass", "password", "--appendfsync", "no", "--save", "", "--appendonly", "no"]
  bump_docker:
    docker:
      - image: circleci/node:12.18.3-stretch



jobs:
  test-backend:
    executor: app_docker
    environment:
      DATABASE_URL: postgresql://root@localhost:5432/testdb
    steps:
      - checkout
      - run_install_dependencies
      - run_lint_check
      - run_test
  bump-version:
    executor: bump_docker
    steps:
      - checkout
      - run_bump_version



workflows:
  build_test:
    jobs:
      - test-backend
      - bump-version:
          name: bump-version
          requires:
            - test-backend
          filters:
            branches:
              only:
                - develop
              ignore: /.*/

