version: 2.1

orbs:
  node: circleci/node@4.1

parameters:
  repo:
    type: string
    default: "lakeside763/acronym-graphql-api"
  dockerfile:
    type: string
    default: Dockerfile.prod

commands:
  run_install_dependencies:
    steps:
      - run:
          name: Install Dependencies
          command: |
            cd ./src/backend
            yarn install
            yarn migrate:test-ci
            yarn prisma generate
  run_lint_check:
    steps:
      - run:
          name: Run Lint Check
          command: |
            cd ./src/backend
            yarn eslint
  run_test:
    steps:
      - run:
          name: Run Unit and Integration testing
          command: |
            cd ./src/backend
            yarn test-ci
  run_bump_version:
    steps:
      - run:
          name: Bump Version
          command: |
            cd ./src/backend
            git config --global user.email "lakeside763@gmail.com"
            git config --global user.name "Olalekan Idowu"
            npm version prerelease --preid=alpha
            git add -A && git commit -m "ci: bumped version number [ci skip]" && git push
  run_docker_login:
    steps:
      - run:
          name: Docker Login
          command: >
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  run_build_and_tag_image:
    steps:
      - run:
          name: Build and Tag Image
          command: |
            cd ./src/backend
            docker-compose build
  run_push_image:
    steps:
      - run:
         name: Push Image
         command: |
          docker push



executors:
  app_docker:
    docker:
      - image: cimg/node:12.18.3
        environment:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          REDIS_PASS: password
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: testdb
      - image: circleci/redis:6.0.8-alpine
        command: ["redis-server", "--requirepass", "password", "--appendfsync", "no", "--save", "", "--appendonly", "no"]
  bump_docker:
    docker:
      - image: circleci/node:12.18.3-stretch
  build_and_push_docker:
    docker:
      - image: circleci/buildpack-deps




jobs:
  test-backend:
    executor: app_docker
    steps:
      - checkout
      - run_install_dependencies
      - run_lint_check
      - run_test
  bump-version:
    executor: bump_docker
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "e5:1a:95:3f:5b:71:d4:74:ce:1a:5e:26:02:f9:30:80"
      - run_bump_version
  build-and-push:
    executor: build_and_push_docker
    steps:
      - checkout
      - run_build_and_tag_image
      - run_docker_login
      - run_push_image





workflows:
  build_test:
    jobs:
      - test-backend
      - bump-version:
          name: bump-version
          requires:
            - test-backend
          filters:
            branches:
              only:
                - develop
              ignore: /.*/
      - build-and-push:
          name: build-and-push
          requires:
            - test-backend
            - bump-version
          filters:
            branches:
              only:
                - develop
              ignore: /.*/

