version: 2.1

orbs:
  node: circleci/node@4.1

commands:
  run_install_dependencies:
    steps:
      - run:
          name: Install Dependencies
          command: |
            cd ./src/backend
            yarn install
            yarn migrate:test-ci
            yarn prisma generate
  run_lint_check:
    steps:
      - run:
          name: Run Lint Check
          command: |
            cd ./src/backend
            yarn eslint
  run_test:
    steps:
      - run:
          name: Run Unit and Integration testing
          command: |
            cd ./src/backend
            yarn test-ci
  run_backend_release:
    steps:
      - run:
          name: Semantic Release
          command: |
            cd ./src/backend
            yarn semantic-release



executors:
  app_docker:
    docker:
      - image: cimg/node:12.18.3
        environment:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          REDIS_PASS: password
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          DATABASE_URL: postgresql://root@localhost:5432/testdb?schema=test
          POSTGRES_USER: root
          POSTGRES_DB: testdb
          POSTGRES_PASSWORD: password
      - image: circleci/redis:6.0.8-alpine
        command: ["redis-server", "--requirepass", "password", "--appendfsync", "no", "--save", "", "--appendonly", "no"]



jobs:
  test-backend:
    executor: app_docker
    environment:
      NODE_ENV: test
      POSTGRES_USER: root
      POSTGRES_DB: testdb
      POSTGRES_PASSWORD: password
    steps:
      - checkout
      - run_install_dependencies
      - run_lint_check
      - run_test
      - run_backend_release


workflows:
  build_test:
    jobs:
      - test-backend

