FROM node:12.18.3-alpine AS base
FROM base AS build
LABEL author="Olalekan Idowu"

WORKDIR /app
ADD ./package.json ./yarn.lock ./
RUN yarn install

# copy node_modules from the build image
FROM base

WORKDIR /app
COPY --from=build /app/node_modules node_modules
ADD . /app

RUN yarn prisma generate

EXPOSE 4000

CMD ["start", "start"]
