version: "3.7"

services:
  web:
    container_name: acronym_api
    image: lakeside763/acronym-graphql-api
    build:
      context: .
      dockerfile: node.dockerfile
      args:
        buildversion: 1
        PACKAGES: "nano wget curl"
    depends_on:
      - postgres
    ports:
      - 4000:4000
      - 9229:9229
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev
    environment:
      DATABASE_URL: postgres://postgres:password@postgres/g2i
      NODE_ENV: production
      PORT: 4000

  postgres:
    container_name: postgres
    image: lakeside763/postgres
    build:
      context: .
      dockerfile: postgres.dockerfile
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: g2i
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password






  # postgres:
  #   container_name: postgres_db
  #   image: postgres.12.8
  #   restart: always
  #   expose:
  #     - "5432"
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_DB: g2i
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - ./pgdata/data:/var/lib/postgresql/data
  #     - ./pgdata/init:/docker-entrypoint-initdb.d







