version: "3.7"

services:
  web:
    image: lakeside763/acronym-graphql-api
    build:
      context: .
      dockerfile: node.dockerfile
      args:
        buildversion: 1
    depends_on:
      - db
    ports:
      - "4000:4000"

  db:
    image: lakeside763/g2i-db
    build:
      context: .
      dockerfile: postgres.dockerfile
    restart: unless-stopped
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: g2i
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./pgdata:/var/lib/postgresql/data

