ALTER TABLE "acronym" DROP COLUMN IF EXISTS "id";
ALTER TABLE "acronym" ADD COLUMN IF NOT EXISTS "id" SERIAL;
ALTER TABLE "acronym" ADD PRIMARY KEY (id);


ALTER TABLE "user" DROP COLUMN IF EXISTS "id";
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS "id" SERIAL;
ALTER TABLE "user" ADD PRIMARY KEY (id);
