CREATE TABLE IF NOT EXISTS "user" (
  id SERIAL,
  email VARCHAR (255) NOT NULL,
  password VARCHAR (255) NOT NULL,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY (id),
  UNIQUE (email)
)
